[2024-04-12T07:19:30.721+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-12T07:19:31.042+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.lookup_entry manual__2024-04-12T07:19:14.791350+00:00 [queued]>
[2024-04-12T07:19:31.095+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.lookup_entry manual__2024-04-12T07:19:14.791350+00:00 [queued]>
[2024-04-12T07:19:31.101+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-12T07:19:31.295+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): lookup_entry> on 2024-04-12 07:19:14.791350+00:00
[2024-04-12T07:19:31.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3861) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-12T07:19:31.392+0000] {standard_task_runner.py:63} INFO - Started process 3991 to run task
[2024-04-12T07:19:31.406+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'lookup_entry', 'manual__2024-04-12T07:19:14.791350+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmp2yh6laec']
[2024-04-12T07:19:31.436+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask lookup_entry
[2024-04-12T07:19:31.671+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.lookup_entry manual__2024-04-12T07:19:14.791350+00:00 [running]> on host 48c2eff06d44
[2024-04-12T07:19:32.451+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='lookup_entry' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T07:19:14.791350+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-12T07:19:14.791350+00:00'
[2024-04-12T07:19:32.460+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-12T07:19:32.469+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-12T07:19:32.474+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo lookup_entry']
[2024-04-12T07:19:32.673+0000] {subprocess.py:86} INFO - Output:
[2024-04-12T07:19:32.688+0000] {subprocess.py:93} INFO - lookup_entry
[2024-04-12T07:19:32.689+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-12T07:19:32.690+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-12T07:19:32.789+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=lookup_entry, execution_date=20240412T071914, start_date=20240412T071931, end_date=20240412T071932
[2024-04-12T07:19:33.003+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-12T07:19:33.116+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-12T07:19:33.124+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
